apiVersion: v2
name: unikorn-common
description: Unikorn common templates to keep dependent charts in check.

type: application

version: 0.1.16

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png
